Profile
Kartikey2011yadav/EduWizTesting-Teacher-Portal pull request #19
Opened 2024-09-29 20:07 UTC by i-s-h-i-k-a

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [ ] Code follows the established coding style guidelines
- [ ] All tests are passing

2024-09-29 21:44 UTC, nishant0708 commented
@i-s-h-i-k-a 
![image](https://github.com/user-attachments/assets/d2717996-e337-47f9-9545-79b3c1d9f4f1)
yeh profile page nhi aayega

2024-09-29 21:46 UTC, nishant0708 requested changes

2024-09-29 21:46 UTC, nishant0708 commented on src/ForgetPassword/Forget.jsx
Remove this Changes

2024-10-02 16:41 UTC, i-s-h-i-k-a commented
@nishant working fine on my system

2024-10-02 17:14 UTC, Kartikey2011yadav commented
🤣🤣🤣🤣🤣🤣

2024-10-02 17:14 UTC, Kartikey2011yadav commented
Ye kya chal raha hai

2024-10-02 18:26 UTC, nishant commented
Please @ the full username. I have no affiliation with this repository

2024-10-02 22:10 UTC, nishant0708 approved these changes

2024-10-02 22:10 UTC, merged